# Generated by Django 4.1.2 on 2022-10-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('_1h', models.CharField(max_length=10)),
                ('_24h', models.CharField(max_length=10)),
                ('_7d', models.CharField(max_length=10)),
                ('market_cap', models.CharField(max_length=10)),
                ('volume24h', models.CharField(max_length=100)),
                ('supply', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('img', models.CharField(max_length=1000)),
            ],
        ),
    ]
